### ISSUE TITLE
[feat] 전체 컴포넌트 UI 구현

### ISSUE THREAD

**Issue by tae100k** [wanted-pre-onboading-10/energy-balance#2]
# TASK CARD

Task Description : 전체 컴포넌트 UI 구현

Date : 2022.02.17

## to-do
[navbar 구현]
- [x] navbar 구현
- [x] navbar 클릭시 Link를 통해 url로 이동 (router 설치 완료 후 작업 예정)
- [x] 클릭된 navbar항목에 border-bottom효과 (router 설치 완료 후 작업 예정)
- [x] 미디어 쿼리 설정

[리스트 페이지 우측 컴포넌트]
- [x] 미디어 쿼리 구현
- [x] 제품명 탭
- [x] 검색에 일치하는 리스트 표시 
- [x] 페이지네이션
- [ ] (시간이 남으면) 하단에 "혹시 찾으시는 제품이 없나요?"도 구현
