### ISSUE TITLE
[feat] 필터 slice, 검색 기록 slice,  필터링된 제품 리스트 selector 함수, 검색 기록 selector 함수 만들기

### ISSUE THREAD

**Issue by hyundonmoon** [wanted-pre-onboading-10/energy-balance#3]
# TASK CARD

Task Description : 검색 관련 slice 및 selector 함수 만들기

Date : 2022-02-17

## to-do

- [x] 검색 필터 슬라이스 만들기 + 관련 reducer 만들기
- [x] 검색 기록 슬라이스 만들기 + 관련 reducer 만들기
- [x] 필터 객체에 맞게 필터링된 제품 배열을 return할 수 있는 selector함수 만들기
- [x] 지난 검색 기록을 return할 수 있는 selector함수 만들기
